# Generated by Django 2.0.6 on 2018-07-26 23:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0002_auto_20151019_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interseccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_normal', models.TextField()),
                ('nom', models.TextField()),
                ('slug', models.SlugField(max_length=150)),
                ('latlng', django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326)),
            ],
        ),
    ]
