# Generated by Django 2.0.6 on 2018-08-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0003_auto_20180726_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='img_cuadrada',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='ciudad'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='img_panorama',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='ciudad'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='lineas',
            field=models.ManyToManyField(blank=True, related_name='ciudades', to='core.Linea'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='recorridos',
            field=models.ManyToManyField(blank=True, related_name='ciudades', to='core.Recorrido'),
        ),
        migrations.AlterField(
            model_name='imagenciudad',
            name='original',
            field=models.ImageField(upload_to='img/ciudades'),
        ),
    ]
