# Generated by Django 2.1.1 on 2018-09-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0005_googlegeocodercache'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='img_cuadrada',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='poi'),
        ),
        migrations.AddField(
            model_name='poi',
            name='img_panorama',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='poi'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='activa',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterUniqueTogether(
            name='googlegeocodercache',
            unique_together={('query', 'ciudad')},
        ),
    ]
