# Generated by Django 2.1.1 on 2018-10-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0007_auto_20181006_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interseccion',
            name='slug',
            field=models.SlugField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='slug',
            field=models.SlugField(max_length=150, null=True),
        ),
    ]
