# Generated by Django 2.1.1 on 2018-10-07 02:32

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0008_auto_20181007_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='tags',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
