# Generated by Django 2.1.4 on 2019-01-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0010_administrativearea'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativearea',
            name='img_cuadrada',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='administrativearea'),
        ),
        migrations.AddField(
            model_name='administrativearea',
            name='img_panorama',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='administrativearea'),
        ),
    ]
