# Generated by Django 2.1.4 on 2019-05-05 13:48

import django.contrib.gis.db.models.fields
from django.db import migrations
from django.contrib.gis.geos import Point


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0011_auto_20190121_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativearea',
            name='geometry_simple',
            field=django.contrib.gis.db.models.fields.GeometryField(default=Point(0, 0), srid=4326),
            preserve_default=False,
        ),
    ]
