# Generated by Django 2.1.4 on 2019-05-05 14:04

from django.db import migrations, models


def delete_administrativeareas(apps, schema_editor):
    AdministrativeArea = apps.get_model('catastro.AdministrativeArea')
    AdministrativeArea.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0012_administrativearea_geometry_simple'),
    ]

    operations = [
        migrations.RunPython(delete_administrativeareas, delete_administrativeareas),
        migrations.RemoveField(
            model_name='administrativearea',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='administrativearea',
            name='rgt',
        ),
        migrations.RemoveField(
            model_name='administrativearea',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='administrativearea',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='administrativearea',
            name='path',
            field=models.CharField(max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrativearea',
            name='depth',
            field=models.PositiveIntegerField(),
        ),
    ]
