# Generated by Django 2.2.1 on 2019-05-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0013_auto_20190505_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='osm_type',
            field=models.CharField(choices=[('r', 'Relation'), ('w', 'Way'), ('n', 'Node')], db_index=True, default='c', max_length=1),
            preserve_default=False,
        ),
    ]
