# Generated by Django 3.0 on 2020-02-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0016_auto_20190605_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativearea',
            name='country_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='interseccion',
            name='country_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='country_code',
            field=models.TextField(null=True),
        ),
    ]
