# Generated by Django 3.0.4 on 2020-04-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0017_auto_20200229_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interseccion',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
