# Generated by Django 2.0.6 on 2018-08-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20151019_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmoderacion',
            name='newStatus',
            field=models.CharField(choices=[('E', 'Esperando Mod'), ('S', 'Aceptado'), ('N', 'Rechazado'), ('R', 'Retirado')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='recorridoproposed',
            name='current_status',
            field=models.CharField(choices=[('E', 'Esperando Mod'), ('S', 'Aceptado'), ('N', 'Rechazado'), ('R', 'Retirado')], default='E', max_length=1),
        ),
    ]
