# Generated by Django 2.1.1 on 2018-10-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20180802_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorridoproposed',
            name='osm_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recorridoproposed',
            name='osm_version',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
