# Generated by Django 2.1.3 on 2018-11-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_auto_20181026_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorridoproposed',
            name='parent',
            field=models.UUIDField(null=True),
        ),
    ]
