# Generated by Django 2.2.1 on 2019-05-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_auto_20181111_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorridoproposed',
            name='linea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Linea'),
        ),
        migrations.AlterField(
            model_name='recorridoproposed',
            name='recorrido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Recorrido'),
        ),
    ]
