# Generated by Django 2.2.1 on 2019-05-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_auto_20190530_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorridoproposed',
            name='fin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recorridoproposed',
            name='inicio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recorridoproposed',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recorridoproposed',
            name='sentido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
