# Generated by Django 2.2.1 on 2019-06-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_auto_20190530_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorridoproposed',
            name='import_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
