# Generated by Django 3.0 on 2020-02-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0012_auto_20190624_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorridoproposed',
            name='country_code',
            field=models.TextField(null=True),
        ),
    ]
