# Generated by Django 2.0.6 on 2018-08-02 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20151208_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='img_cuadrada',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='linea'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='img_panorama',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='linea'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='img_cuadrada',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='recorrido'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='img_panorama',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='recorrido'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridos', to='core.Linea'),
        ),
    ]
