# Generated by Django 2.1.1 on 2018-09-28 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180802_0105'),
        ('core', '0004_auto_20180729_1838'),
    ]

    operations = [
    ]
