# Generated by Django 2.1.1 on 2018-10-20 19:12

from django.db import migrations, models
from django.conf import settings


def add_osm_bot_user(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    User.objects.get_or_create(
        email='osm_bot@cualbondi.com.ar',
        username='osmbot'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recorrido_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrido',
            name='osm_version',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(add_osm_bot_user),
    ]
