# Generated by Django 2.1.1 on 2018-10-26 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recorrido_osm_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrido',
            name='ruta_last_updated',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.RemoveField(
            model_name='recorrido',
            name='last_updated',
        ),
        migrations.RunSQL("""
            UPDATE core_recorrido
            SET ruta_last_updated = (
                select
                    max(er.date_update) as date_update
                from
                    editor_recorridoproposed er
                join
                    editor_logmoderacion lm on (lm."recorridoProposed_id" = er.id)
                where
                    core_recorrido.uuid = er.parent
                and
                    lm."newStatus" = 'S'
            )
        """),
        migrations.RunSQL("""
            UPDATE core_recorrido
            SET ruta_last_updated = '2010-01-01'
            WHERE ruta_last_updated is null
        """)
    ]
