# Generated by Django 2.1.1 on 2018-10-26 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_recorrido_ruta_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorrido',
            name='ruta_last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
