# Generated by Django 2.1.1 on 2018-10-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181026_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImporterLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(blank=True, null=True)),
                ('osm_version', models.BigIntegerField(blank=True, null=True)),
                ('osm_timestamp', models.DateTimeField(blank=True, null=True)),
                ('run_timestamp', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('proposed', models.BooleanField()),
                ('accepted', models.BooleanField()),
                ('proposed_reason', models.TextField(blank=True, null=True)),
                ('accepted_reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
