# Generated by Django 2.1.2 on 2018-10-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181028_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='importerlog',
            name='osm_administrative',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importerlog',
            name='osm_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunSQL(
            [("""
                CREATE FUNCTION array_distinct(anyarray) RETURNS anyarray AS $f$
                    SELECT array_agg(DISTINCT x) FROM unnest($1) t(x);
                $f$ LANGUAGE SQL IMMUTABLE;
            """)],
            [("""
                DROP FUNCTION array_distinct;
            """)]
        )
    ]
