# Generated by Django 2.1.4 on 2019-04-19 18:19

from django.db import migrations, models
from django.urls import reverse

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181028_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='osm_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
