# Generated by Django 2.2.1 on 2019-05-30 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190419_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorrido',
            name='linea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recorridos', to='core.Linea'),
        ),
    ]
