# Generated by Django 2.2.1 on 2019-05-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190530_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorrido',
            name='fin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='inicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='sentido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
