# Generated by Django 2.2.1 on 2019-06-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190605_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='importerlog',
            name='king',
            field=models.TextField(blank=True, null=True),
        ),
    ]
