# Generated by Django 2.2.1 on 2019-06-18 20:53

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_importerlog_king'),
    ]

    operations = [
        CreateExtension('unaccent'),
    ]
