# Generated by Django 3.0 on 2020-02-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_recorrido_paradas'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='country_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='parada',
            name='country_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='country_code',
            field=models.TextField(null=True),
        ),
    ]
